version: '3.1'

services:

  # server:
  #   context:
  #     build: .
  #   environment:
  #     DB_CONNECTION_STRING: monogodb://localhost/splack
  #     DB_PASSWORD: example

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080